platform :ios, "15.0"
use_frameworks! :linkage => :static
install! "cocoapods", :warn_for_unused_master_specs_repo => false

target "CombineSupplementExample" do
  pod "CombineSupplement", :path => ".."

  pod 'SwiftLint', :configurations => ['Debug']
end

def set_deployment_target(target)
  target.build_configurations.each do |config|
    config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    set_deployment_target(target)
  end
end
